"""add_knowledge_graph_and_suggested_prompts

Revision ID: 0557b8277f20
Revises: 88824120c595
Create Date: 2026-07-21 22:08:26.728598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0557b8277f20'
down_revision: Union[str, Sequence[str], None] = '88824120c595'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('first_mentioned_recording_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['first_mentioned_recording_id'], ['recordings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entities_patient_id'), 'entities', ['patient_id'], unique=False)
    op.create_table('entity_mentions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('recording_id', sa.UUID(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recording_id'], ['recordings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entity_mentions_entity_id'), 'entity_mentions', ['entity_id'], unique=False)
    op.create_index(op.f('ix_entity_mentions_recording_id'), 'entity_mentions', ['recording_id'], unique=False)
    op.create_table('entity_relationships',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('entity_id_a', sa.UUID(), nullable=False),
    sa.Column('entity_id_b', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(), nullable=False),
    sa.Column('source_recording_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['entity_id_a'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity_id_b'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_recording_id'], ['recordings.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suggested_prompts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('prompt_text', sa.String(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suggested_prompts_patient_id'), 'suggested_prompts', ['patient_id'], unique=False)
    op.add_column('caregiver_patient_access', sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False))
    op.add_column('caregiver_patient_access', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('patients', 'pin_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('recordings', sa.Column('classification_confidence', sa.Float(), nullable=True))
    op.add_column('recordings', sa.Column('classification_rationale', sa.String(), nullable=True))
    op.add_column('recordings', sa.Column('model_identifier', sa.String(), nullable=True))
    op.add_column('recordings', sa.Column('prompt_version', sa.String(), nullable=True))
    op.add_column('recordings', sa.Column('failure_stage', sa.String(), nullable=True))
    op.alter_column('recordings', 'transcript',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('recordings', 'processing_status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('recordings', 'processing_status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('recordings', 'transcript',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('recordings', 'failure_stage')
    op.drop_column('recordings', 'prompt_version')
    op.drop_column('recordings', 'model_identifier')
    op.drop_column('recordings', 'classification_rationale')
    op.drop_column('recordings', 'classification_confidence')
    op.alter_column('patients', 'pin_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('caregiver_patient_access', 'created_at')
    op.drop_column('caregiver_patient_access', 'id')
    op.drop_index(op.f('ix_suggested_prompts_patient_id'), table_name='suggested_prompts')
    op.drop_table('suggested_prompts')
    op.drop_table('entity_relationships')
    op.drop_index(op.f('ix_entity_mentions_recording_id'), table_name='entity_mentions')
    op.drop_index(op.f('ix_entity_mentions_entity_id'), table_name='entity_mentions')
    op.drop_table('entity_mentions')
    op.drop_index(op.f('ix_entities_patient_id'), table_name='entities')
    op.drop_table('entities')
    # ### end Alembic commands ###
