"""add model_identifier and prompt_version to entity_mentions

Revision ID: 3c539ade7f01
Revises: 1b142365cbd1
Create Date: 2026-07-21 22:26:18.401457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c539ade7f01'
down_revision: Union[str, Sequence[str], None] = '1b142365cbd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entity_mentions', sa.Column('model_identifier', sa.String(), nullable=True))
    op.add_column('entity_mentions', sa.Column('prompt_version', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entity_mentions', 'prompt_version')
    op.drop_column('entity_mentions', 'model_identifier')
    # ### end Alembic commands ###
